apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m184tm5h2-dotnet-basic
  janus-idp.io/tekton: m184tm5h2-dotnet-basic
  backstage.io/kubernetes-id: m184tm5h2-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m184tm5h2-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
